version: "3.8"

services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ..:/workspace:cached
    depends_on:
      - mongo
    command: sleep infinity

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
